### ISSUE TITLE
Progress Bar/Loader

### ISSUE THREAD

**Issue by Mannan-Goyal** [IEEE-VIT/templa-rs#10]
Implement a progress bar or a pre-loader predominantly to be used when the repository is being cloned. But make sure to make it an independent and modular function so that other functions can call it in case it is needed.

**Comment by mooyg** [comment]
https://github.com/rust-lang/git2-rs
can I use this library to provide me helper functions for the progress bars?

**Comment by mintbomb27** [comment]
Sure go ahead! Assigning the issue.

**Comment by mooyg** [comment]
I don't understand what `submodules.json` is for now I have done the progress bar pretty much but have one issue where I need to get the size of the repo for that I am using github api to make a request and get the size before hand and initialize loader but for that I need the username of the person who created the repo I made these changes to the `submodules.json` thinking they were getting mapped initially but that doesn't seem to be the case 
```json
[
  {
    "name": "react-boilerplate",
    "url": "https://github.com/react-boilerplate/react-boilerplate",
    "tags": ["react", "reactjs"],
    "owner": "react-boilerplate"
  },
  {
    "name": "node-boilerplate",
    "url": "https://github.com/hagopj13/node-express-boilerplate",
    "tags": ["node", "nodejs"],
    "owner": "hagopj13"
  },
  {
    "name": "jquery-boilerplate",
    "url": "https://github.com/jquery-boilerplate/jquery-boilerplate",
    "tags": ["jquery", "jqueryjs", "js"],
    "owner": "jquery-boilerplate"
  },
  {
    "name": "android-boilerplate",
    "url": "https://github.com/ribot/android-boilerplate",
    "tags": ["android", "mvvm", "rxjava"],
    "owner": "ribot"
  }
]
```
thinking we might be passing down `url` and stuff from here but that doesn't seem to be the case not really familiar with tui and stuff. So can you tell me the use of this json file?

**Comment by Mannan-Goyal** [comment]
@mooyg we use the type argument to only list the templates which are relevant to the type of project passed using the -t/--type flag in the command hence just running cargo run should and is not returning the template_list
