### ISSUE TITLE
Implement new design for the TUI

### ISSUE THREAD

**Issue by mintbomb27** [IEEE-VIT/templa-rs#3]
Make a UI design for the TUI in a design software like Figma, Adobe Xd, or Sketch.

We're looking for a design where we can accommodate a search bar, a list view of the available templates, and a preview of the boilerplate repository if possible. Any further additions are welcome.

Give a link to your design file in the README while making the PR, and make sure the link that you give is made public. (You may also include screenshots of the design in the PR if you wish)

**Comment by BRO3886** [comment]
Hello, this took me 5-10 minutes to ideate and make, love this, I'll learn some rust and try to contribute
:link: : [Figma Link](https://www.figma.com/file/2VfxFGTk2FqLJiMExB7u9P/templa-rs?node-id=0%3A1)

I think showing some repo stats is a good idea, I'd love to know about the number of open issues and stars atleast

Screenshot:

![image](https://user-images.githubusercontent.com/39856034/135727066-ff0508c0-662b-46bd-97d1-04fefca6755b.png)

**Comment by BRO3886** [comment]
I'll make this a PR if I'm short on hacktoberfest contributions :wink:

**Comment by mintbomb27** [comment]
Lol. They look great! Thanks a lot for the contribution! You can go ahead and open a PR with just the figma link, and we'd be happy to accept it :)

**Comment by BRO3886** [comment]
Should I put it in the readme?

**Comment by mintbomb27** [comment]
Yes, definitely! BTW, If you could add some colour in the designs, would be great!

**Comment by BRO3886** [comment]
> Yes, definitely! BTW, If you could add some colour in the designs, would be great!

sure, should I go with hacktoberfest theme?

**Comment by BRO3886** [comment]
![image](https://user-images.githubusercontent.com/39856034/136071155-634f36d4-0003-4501-8345-4311a1bbe5a4.png)

**Comment by mintbomb27** [comment]
closing as complete.
