### ISSUE TITLE
[BUG] Unable to release templa-rs

### ISSUE THREAD

**Issue by DarthBenro008** [IEEE-VIT/templa-rs#37]
**Describe the bug**

Currently, templa-rs uses `submodules.json` file to load and display the available templates, but while creating a release, this is not included, hence it isn't ready to ship solution yet.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build templa-rs using `cargo build`
2. Place the binary in a directory where there isn't any `submodules.json`

**Expected behaviour**
It should at least have a minimal amount of repos already pre-built for user to select

**Screenshots**
![image](https://user-images.githubusercontent.com/31009634/136316089-8b727fdd-ce8f-425e-8b88-87bde2474dd2.png)

**Desktop (please complete the following information):**
 - OS: Linux/Windows

**Proposed Solution(s)**
1. Refer to the `submodules.json` file from GitHub while running the command
1. Create a small key/value storage and store the data (serialize and deserialize on startup)

**Comment by mintbomb27** [comment]
@DarthBenro008 If there was a request failure, it would've shown the same. From your screenshot, it also shows that you're using the old UI as well.

And the default branch is `master`? Not `main`?😅

**Comment by DarthBenro008** [comment]
Oops, it seems there was some aggressive `cargo build` cache. removing target and re-building seemed to produce latest build :+1:
