### ISSUE TITLE
Implement Live Search

### ISSUE THREAD

**Issue by Mannan-Goyal** [IEEE-VIT/templa-rs#4]
For now the search parameter is being taken as a flag (-t/--type), instead implement a input box in TUI and return matching results on every keypress. A reference for the same can be found [here.](https://github.com/Rigellute/spotify-tui)

**Comment by Daemondeal** [comment]
I'm working on this, can you assign it to me? Will probably look into #2 and #5 after I'm done. I'm following the design suggested in #3.

**Comment by mintbomb27** [comment]
Hey sure! Thanks a lot for showing interest! Assigning.
