### ISSUE TITLE
Fetching the submodules.json dynamically from the repo

### ISSUE THREAD

**Issue by mintbomb27** [IEEE-VIT/templa-rs#7]
Currently, the `submodules.json` is static with the version of the compiled binary. If any changes in the `submodules.json` is made in the repo, the updated results aren't shown to the users.

To solve this, fetch the [submodules.json](https://github.com/IEEE-VIT/templa-rs/blob/30b6b993bc5c77f450820b45118ff999d6f3afa4/submodules.json) from the repository and display live results.

**Comment by Celeo** [comment]
Would the fetch happen at the start of [`tui::render_tui`](https://github.com/IEEE-VIT/templa-rs/blob/5d66ae044c7687c6f0247b81dcbb4157483c6dd7/src/tui.rs#L27)?

**Comment by mintbomb27** [comment]
Hey! Thanks a lot for showing interest.

The fetch can either happen at `render_tui()`, or before the rendering in [`main()`](https://github.com/IEEE-VIT/templa-rs/blob/5d66ae044c7687c6f0247b81dcbb4157483c6dd7/src/main.rs#L20).
