### ISSUE TITLE
Implement ASCII Art

### ISSUE THREAD

**Issue by mintbomb27** [IEEE-VIT/templa-rs#9]
Design an ASCII Art Logo with the name "Templa-rs".

Add it to the TUI preferably as a block as well as in the help command output.

**Comment by aswinikalyan30** [comment]
Can i work on this?

**Comment by vini-fda** [comment]
Hey there! Can you assign this issue to me?

Also, how should it scale with the size of the terminal? Or should it be fixed-size?

**Comment by mintbomb27** [comment]
Hey @vini-fda ! Thank you for showing interest! It can be of a fixed size that isn't too small or too big. If you could scale it with the terminal, then great! It can be multicolored. Do check the design at #3 and try to accommodate a block where you can add the art.

Assigning the issue.

**Comment by vini-fda** [comment]
Ok, cool! I'm thinking something like [oh-my-zsh's ASCII logo](https://github.com/ohmyzsh/ohmyzsh/blob/098bcda6910aa2f734fb0ad59ac089157a239c87/tools/upgrade.sh). Do you guys have an "official font" in mind, as a reference? Currently I'm using FiraCode, which has ligatures(but obviously using ligature features in the ASCII art would make it non-accessible for others, so I'm not doing that).

I've also taken the liberty of using [this website](https://texteditor.com/ascii-art/) and [this one](https://textart.me/) for inspiration for the ASCII art. Here are some outputs with my font in my terminal(with some slight modifications):

![image](https://user-images.githubusercontent.com/20410205/136044308-744ecb98-fd31-4492-818a-7a2ae0528326.png)

**Comment by mintbomb27** [comment]
Hey @vini-fda yeah adding to the `command.yml` works. If you could also add to the README, would be great! The rainbow version, I'm not sure if it'll support a lot of terminals? If adding that to the command.yml works, then please go for it. But make sure it supports all the terminals.
